# TODO: pin dependency versions
name: antspy
dependencies:
- pandas
- pyyaml
- numpy
- scikit-image
- scikit-learn
- statsmodels
- matplotlib
- Pillow
- packaging
- pip
- pip:
  - nibabel
  - webcolors